config/routes.rb
Rails.application.routes.draw do

  resources :transactions do
    collection do
      get :view_all
    end
    get :get_details, :on=>:member
    get :to_print_pdf, :on=>:member
  end

  resources :accounts do
    collection do
      get :pdf_export
    end
  end

  resources :dashboard

  resources :users
  resources :user_sessions

  match 'login', :to => 'user_sessions#new', :via => [:get]
  match 'logout', :to => 'user_sessions#destroy', :via => [:get]

  resources :roles do
    get :approve, :on=>:member
  end

  root 'user_sessions#new'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments

  #validations
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 100}
  validates :reference_code, :presence => true, :uniqueness => true, :length => {:maximum => 10}
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_filter :require_user

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)
    @role.reference_code = params[:role][:reference_code].downcase
    @role.created_by = current_user.id

    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_path, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    @role = Role.find(params[:id])
    @role.update_attribute('status', @role.status ? false : true)
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description, :reference_code, :status, :created_by, :modified_by)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= bootstrap_form_for(@role) do |f| %>
    <%= f.text_field :name, placeholder: 'Enter Name of Role' %>
    <%= f.text_field :description, placeholder: 'Enter Description of Role' %>
    <%= f.text_field :reference_code, help: 'Example: Admin', placeholder: 'Enter Reference Code' %>
    <%= f.submit 'Submit' %>
<% end %>

app/views/roles/approve.js.erb
$("#status_<%=@role.id%>").html("<%=escape_javascript(link_to @role.status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_role_path,:remote=>true)%>");

app/views/roles/edit.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      Roles
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>
      </li>
      <li>
        <i class="fa fa-table"></i>  <%= link_to 'Roles', roles_path %>
      </li>

      <li class="active">
        <i class="fa fa-table"></i> Edit Role Details
      </li>
    </ol>
  </div>
</div>
<!-- Page Heading -->

<div class="panel panel-default">
  <div class="panel-heading">
    Edit Role Details
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>
<%= link_to roles_path, class: 'btn btn-success' do %>
    <i class='glyphicon glyphicon-arrow-left'></i> Back to Roles
<% end %>

app/views/roles/index.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      Roles
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>
      </li>
      <li class="active">
        <i class="fa fa-table"></i> Roles
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->
<% i=1 %>

<%= flash_messages %>

<%= link_to new_role_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-plus"></i> New Role
<% end %>
<br/>
<br/>
<div class="panel panel-default">
  <div class="panel-heading">
    Available Roles
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <% if @roles.blank? %>
        <div class="alert alert-danger">
          <strong>OPPS!</strong> There are no Roles in the System.
        </div>
    <% else %>
        <div class="table-responsive">

          <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
              <th>#</th>
              <th>STATUS</th>
              <th>NAME</th>
              <th>DESCRIPTION</th>
              <th>REFERENCE CODE</th>
              <th colspan="3">ACTIONS</th>
            </tr>
            </thead>
            <tbody>
            <% @roles.each do |role| %>
                <tr>
                  <td><%= i %></td>
                  <td>
                    <div id="status_<%= role.id %>">
                      <%= link_to role.status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_role_path(role), :remote=>true %>
                    </div>

                  </td>
                  <td><%= role.name %></td>
                  <td><%= role.description %></td>
                  <td><%= role.reference_code %></td>
                  <td><%= link_to 'View', role, class: 'btn btn-info btn-xs' %> |
                    <%= link_to 'Edit', edit_role_path(role), class: 'btn btn-warning btn-xs' %> |
                    <%= link_to 'Delete', role, method: :delete, data: {confirm: 'Are you sure to delete the Record?'}, class: 'btn btn-danger btn-xs' %></td>
                </tr>
                <% i = i + 1 %>
            <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
  </div>
</div>

app/views/roles/new.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      Roles
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>

      </li>
      <li>
        <i class="fa fa-table"></i>  <%= link_to 'Roles', roles_path %>
      </li>

      <li class="active">
        <i class="fa fa-table"></i> Add New Roll
      </li>
    </ol>
  </div>
</div>
<!-- Page Heading -->

<div class="panel panel-default">
  <div class="panel-heading">
    Add New Role
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>
<%= link_to roles_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-arrow-left"></i> Back to Roles
<% end %>

app/views/roles/show.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      States
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>

      </li>
      <li>
        <i class="fa fa-table"></i>  <%= link_to 'Roles', roles_path %>
      </li>

      <li class="active">
        <i class="fa fa-table"></i> Role Details
      </li>
    </ol>
  </div>
</div>
<!-- Page Heading -->

<div class="panel panel-default">
  <div class="panel-heading">
    Details
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">

      <table class="table table-striped table-bordered">
        <tbody>
        <tr>
          <td data-field="name" data-halign="right" data-align="center">Name of State</td>
          <td><%= @role.name %></td>
        </tr>
        <tr>
          <td data-field="stargazers_count" data-halign="center" data-align="left">Description</td>
          <td><%= @role.description %></td>
        </tr>
        <tr>
          <td data-field="forks_count" data-halign="left" data-align="right">Reference Code</td>
          <td><%= @role.reference_code %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to roles_path, class: 'btn btn-success' do %>
    <i class='glyphicon glyphicon-arrow-left'></i> Back to Roles
<% end %>&#09;
<%= link_to 'Edit', edit_role_path(@role), class: 'btn btn-warning' %>