config/routes.rb
Rails.application.routes.draw do

  resources :transactions do
    collection do
      get :view_all
    end
    get :get_details, :on=>:member
    get :to_print_pdf, :on=>:member
  end

  resources :accounts do
    collection do
      get :pdf_export
    end
  end

  resources :dashboard

  resources :users
  resources :user_sessions

  match 'login', :to => 'user_sessions#new', :via => [:get]
  match 'logout', :to => 'user_sessions#destroy', :via => [:get]

  resources :roles do
    get :approve, :on=>:member
  end

  root 'user_sessions#new'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def view_all
  #  @transactions = Transaction.group(:transaction_date).count.sort.reverse
    @transactions = Transaction.group(:transaction_date).where('amount <? ', 0).sum(:amount)

  end

  def get_details
    @transactions = Transaction.where(:transaction_date => params[:id])
  end

  def to_print_pdf
    @transactions = Transaction.where('amount <=? AND transaction_date =?', -1000, params[:id].to_date)
#    @transactions = Transaction.where(:transaction_date => params[:id])
    html = render_to_string :layout => false
    kit = PDFKit.new(html, page_size: 'A4', orientation: 'Landscape')
    kit.stylesheets << Rails.root.join('public', 'stylesheets', 'styles.css') #'/public/stylesheets/styles.css'
    send_data(kit.to_pdf, :filename => 'Account_Statement_'+ params[:id] +'.pdf', :type => 'application/pdf')
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def transaction_params
    params[:transaction]
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/get_details.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      CSP Transaction Management
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>
      </li>
      <li>
        <%= link_to view_all_transactions_path do %>
            <i class="fa fa-list"></i> CSP Transaction Management
        <% end %>
      </li>

      <li class="active">
        <i class="fa fa-list-alt"></i> CSP Transactions Details
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->
<% i=1 %>

<%= flash_messages %>

<div class="panel panel-default">
  <div class="panel-heading">
    CSP Transactions details on : <b><%= Date.parse(params[:id]).strftime("%d-%m-%Y") %> </b>
  </div>
  <!-- /.panel-heading -->

  <div class="panel-body">
    <%= link_to pdf_export_accounts_path, class: 'btn btn-primary' do %>
        <i class="glyphicon glyphicon-save"></i> Export PDF
    <% end %>
    <% if @transactions.blank? %>
        <div class="alert alert-danger">
          <strong>OPPS!</strong> There are no CSP Transactions in the System.
        </div>
    <% else %>
        <div class="table-responsive">

          <table class="table table-bordered table-hover table-striped"
                 data-toggle="table"
                 data-cache="true"
                 data-url="data1.json"
                 data-height="400"
                 data-pagination="true"
                 data-show-refresh="true"
                 data-show-columns="true"
                 data-search="true"
          >
            <thead>
            <tr>
              <th>#</th>
              <th>DATE</th>
              <th>CSP CODE</th>
              <th>HOLDING AMOUNT</th>
            </tr>
            </thead>
            <tbody>
            <% @transactions.each do |transaction| %>
                <tr>
                  <td><%= i %></td>
                  <td><%= transaction.transaction_date.strftime("%d-%m-%Y") %></td>
                  <td><%= transaction.csp_code %></td>
                  <td><%= transaction.amount %></td>
                </tr>
                <% i = i + 1 %>
            <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
  </div>
</div>

app/views/transactions/index.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      CSP Transaction Management
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>
      </li>
      <li class="active">
        <i class="fa fa-table"></i> CSP Transaction Management
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->
<% i=1 %>

<%= flash_messages %>

<div class="panel panel-default">
  <div class="panel-heading">
    Available CSP Transactions
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <% if @transactions.blank? %>
        <div class="alert alert-danger">
          <strong>OPPS!</strong> There are no CSP Transactions in the System.
        </div>
    <% else %>
        <div class="table-responsive">

          <table class="table table-bordered table-hover table-striped"
                 data-toggle="table"
                 data-cache="true"
                 data-url="data1.json"
                 data-height="400"
                 data-pagination="true"
                 data-show-refresh="true"
                 data-show-columns="true"
                 data-search="true"
          >
            <thead>
            <tr>
              <th>#</th>
              <th>DATE</th>
              <th>CSP CODE</th>
              <th>HOLDING AMOUNT</th>
            </tr>
            </thead>
            <tbody>
            <% @transactions.each do |transaction| %>
                <tr>
                  <td><%= i %></td>
                  <td><%= transaction.transaction_date %></td>
                  <td><%= transaction.csp_code %></td>
                  <td><%= transaction.amount %></td>
                </tr>
                <% i = i + 1 %>
            <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
  </div>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/to_print_pdf.html.erb
<% i=1 %>
<% total = 0 %>
<p align="center">CSP Fund Transfer Statement of <%= Date.parse(params[:id]).strftime("%d-%m-%Y") %> </p>
<% if @transactions.blank? %>
    <strong>OPPS!</strong> There are no CSP Transactions in the System.
<% else %>
    <table>
      <thead>
      <tr>
        <th>#</th>
        <th>CSP Code</th>
        <th>Name</th>
        <th>Account Number</th>
        <th>Code</th>
        <th>Amount</th>
      </tr>
      </thead>
      <tbody>
      <% @transactions.each do |transaction| %>
          <tr>
            <td><%= i %></td>
            <td><%= transaction.csp_code %></td>
            <td><%= get_csp_name(transaction) %></td>
            <td><%= get_csp_account_number(transaction) %></td>
            <td><%# get_csp_branch_code(transaction) %></td>
            <% amount = (-1) * transaction.amount %>
            <td align="right">
              <% amount= amount % 100 == 0 ? amount : amount - (amount % 100) %>
              <%= amount.abs.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %>
            </td>
            <% total += amount %>
          </tr>
          <% i = i + 1 %>
      <% end %>
      <tr>
        <td colspan="5" align="right">Total:</td>
        <td align="right"><%= total.abs.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,") %></td>
      </tr>
      </tbody>
    </table>
<% end %>

app/views/transactions/view_all.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      CSP Transaction Management
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>
      </li>
      <li class="active">
        <i class="fa fa-list"></i> CSP Transaction Management
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->
<% i=1 %>

<%= flash_messages %>
<br/>
<br/>
<div class="panel panel-default">
  <div class="panel-heading">
    Available CSP EOD Transactions (Date Wise)
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <% if @transactions.blank? %>
        <div class="alert alert-danger">
          <strong>OPPS!</strong> There are no Transactions in the System.
        </div>
    <% else %>
        <div class="table-responsive">

          <table class="table table-bordered table-hover table-striped"
                 data-toggle="table"
                 data-cache="true"
                 data-url="data1.json"
                 data-height="555"
                 data-pagination="true"
                 data-show-refresh="true"
                 data-show-columns="true"
                 data-search="true"
          >
            <thead>
            <tr>
              <th>#</th>
              <th>DATE</th>
              <th>CSP Participate</th>
              <th data-align="right" data-halign="left">Amount</th>
              <th colspan="3">ACTIONS</th>
            </tr>
            </thead>
            <tbody>
            <% @transactions.each do |trans| %>
                <tr>
                  <td><%= i %></td>
                  <td><%= trans[0].strftime("%d-%m-%Y") %></td>
                  <td><%# trans[1] %></td>
                  <td><%= trans[1].abs.to_s.gsub(/(\d+?)(?=(\d\d)+(\d)(?!\d))(\.\d+)?/, "\\1,")%></td>
                  <td><%= link_to 'View Transactions', {:action => :get_details, :id=>trans[0]}, class: 'btn btn-info btn-xs' %>
                    <%= link_to 'Export PDF' , {:action => :to_print_pdf, :id=>trans[0]}, class:'btn btn-warning btn-xs' %>
                    <%= link_to 'Export TEXT' , {:action => :to_print_pdf, :id=>trans[0]}, class:'btn btn-success btn-xs' %>
                  </td>
                </tr>
                <% i = i + 1 %>
            <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
  </div>
</div>