config/routes.rb
Rails.application.routes.draw do

  resources :transactions do
    collection do
      get :view_all
    end
    get :get_details, :on=>:member
    get :to_print_pdf, :on=>:member
  end

  resources :accounts do
    collection do
      get :pdf_export
    end
  end

  resources :dashboard

  resources :users
  resources :user_sessions

  match 'login', :to => 'user_sessions#new', :via => [:get]
  match 'logout', :to => 'user_sessions#destroy', :via => [:get]

  resources :roles do
    get :approve, :on=>:member
  end

  root 'user_sessions#new'

end

app/views/common/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="dashboard">VEDAVAAG</a>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">

    <!-- /.dropdown -->
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
        </li>
        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
        </li>
        <li class="divider"></li>
        <li>         <%= link_to logout_path do %>
              <i class="fa fa-fw fa-power-off"></i> Sign Out
          <% end %>
        </li>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->



  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li class="sidebar-search">
          <!-- /input-group -->
        </li>
        <li>
          <%= link_to dashboard_index_path do %>
              <i class="fa fa-home"></i> Home
          <% end %>
        </li>
        <li>
          <a href="#"><i class="fa fa-bars fa-fw"></i> General<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to 'Transactions', view_all_transactions_path %>
            </li>
            <li>
              <%= link_to 'CSP Accounts', accounts_path %>
            </li>
            <li>
              <%= link_to 'Users', users_path %>
            </li>
            <li>
              <%= link_to 'Roles', roles_path %>
            </li>
          </ul>
          <!-- /.nav-second-level -->
        </li>

      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/common/_header_1.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="dashboard">VEDAVAAG</a>
  </div>
  <!-- Top Menu Items -->
  <ul class="nav navbar-right top-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
      <ul class="dropdown-menu alert-dropdown">
        <li>
          <a href="#"><i class="fa fa-fw  fa-info-circle "></i> Help</a>
        </li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">

        <i class="fa fa-user"></i> <%= current_user.name %>
        <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
          <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to logout_path do %>
              <i class="fa fa-fw fa-power-off"></i> Sign Out
          <% end %>
        </li>
      </ul>
    </li>
  </ul>
  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
      <li class="active">
        <a href="#"><i class="fa fa-fw fa-dashboard"></i> Home</a>

      </li>
      <li>
        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> General
          <i class="fa fa-fw fa-caret-down"></i></a>
        <ul id="demo" class="collapse">

          <li>
            <%= link_to 'Transactions', view_all_transactions_path %>
          </li>
          <li>
            <%= link_to 'CSP Accounts', accounts_path %>
          </li>
          <li>
            <%= link_to 'Users', users_path %>
          </li>
          <li>
            <%= link_to 'Roles', roles_path %>
          </li>

        </ul>
      </li>

    </ul>
  </div>
  <!-- /.navbar-collapse -->
</nav>


<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">