config/routes.rb
Rails.application.routes.draw do

  resources :transactions do
    collection do
      get :view_all
    end
    get :get_details, :on=>:member
    get :to_print_pdf, :on=>:member
  end

  resources :accounts do
    collection do
      get :pdf_export
    end
  end

  resources :dashboard

  resources :users
  resources :user_sessions

  match 'login', :to => 'user_sessions#new', :via => [:get]
  match 'logout', :to => 'user_sessions#destroy', :via => [:get]

  resources :roles do
    get :approve, :on=>:member
  end

  root 'user_sessions#new'

end

app/models/account.rb
class Account < ActiveRecord::Base
  #validations
  validates :csp_code, :presence => true, :uniqueness => true, :length => {:maximum => 10}

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
=begin
    html = render_to_string :layout => false
    kit = PDFKit.new(html)
    kit.stylesheets << Rails.root.join('public','stylesheets','styles.css')#'/public/stylesheets/styles.css'
    send_data(kit.to_pdf, :filename => 'Seva.pdf', :type => 'application/pdf')
=end
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pdf_export
    @accounts = Account.all
    html = render_to_string :layout => false
    kit = PDFKit.new(html, page_size: 'A4', orientation: 'Landscape')
    kit.stylesheets << Rails.root.join('public', 'stylesheets', 'styles.css') #'/public/stylesheets/styles.css'
    send_data(kit.to_pdf, :filename => 'CSP_Account_Details.pdf', :type => 'application/pdf')

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:csp_code, :name, :account_number, :status, :created_by, :modified_by)

  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= bootstrap_form_for(@account) do |f| %>
    <%= f.text_field :csp_code, placeholder: 'Enter CSP Code', label: 'Enter CSP Code'%>
    <%= f.text_field :name, placeholder: 'Enter Name of CSP',label: 'Enter CSP Name' %>
    <%= f.text_field :mobile, placeholder: 'Enter Mobile Number',label: 'Enter Mobile Number' %>
    <%= f.text_field :state, placeholder: 'Enter State',label: 'Enter State' %>
    <%= f.text_field :location, placeholder: 'Enter Location of CSP',label: 'Enter CSP Location' %>
    <%= f.text_field :address, placeholder: 'Enter Address of CSP',label: 'Enter Address of CSP' %>
<hr>
    <%= f.text_field :account_number, placeholder: 'Enter Account Number as per Records' ,label: 'Enter Bank Account'%>
    <%= f.text_field :bank_name, placeholder: 'Enter Name of Bank',label: 'Enter Name of Bank' %>
    <%= f.text_field :branch_name, placeholder: 'Enter Name of Branch',label: 'Enter Name of Branch' %>
    <%= f.text_field :ifsc, placeholder: 'Enter IFSC',label: 'Enter IFSC' %>
    <%= f.submit 'Submit' %>

<% end %>

app/views/accounts/edit.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      CSP Accounts
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>
      </li>
      <li>
        <i class="fa fa-table"></i>  <%= link_to 'CSP Accounts', accounts_path %>
      </li>

      <li class="active">
        <i class="fa fa-table"></i> Edit CSP Account Details
      </li>
    </ol>
  </div>
</div>
<!-- Page Heading -->

<div class="panel panel-default">
  <div class="panel-heading">
    Edit Account Details
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>
<%= link_to accounts_path, class: 'btn btn-success' do %>
    <i class='glyphicon glyphicon-arrow-left'></i> Back to CSP Accounts
<% end %>

app/views/accounts/index.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      CSP Account Management
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>
      </li>
      <li class="active">
        <i class="fa fa-list"></i> CSP Account Management
      </li>
    </ol>
  </div>
</div>
<!-- /.row -->
<% i=1 %>

<%= flash_messages %>

<%= link_to new_account_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-plus"></i> New CSP Account
<% end %>
&#09;
<%= link_to pdf_export_accounts_path, class: 'btn btn-primary' do %>
        <i class="glyphicon glyphicon-save"></i> Export PDF
<% end %>
<br/>
<br/>
<div class="panel panel-default">
  <div class="panel-heading">
    Available CSP Accounts
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <% if @accounts.blank? %>
        <div class="alert alert-danger">
          <strong>OPPS!</strong> There are no CSP Accounts in the System.
        </div>
    <% else %>
        <div class="table-responsive">

          <table class="table table-bordered table-hover table-striped"
                 data-toggle="table"
                 data-cache="true"
                 data-url="data1.json"
                 data-height="400"
                 data-pagination="true"
                 data-show-refresh="true"
                 data-show-columns="true"
                 data-search="true"
          >
            <thead>
            <tr>
              <th>#</th>
              <th>CSP CODE</th>
              <th>NAME</th>
              <th>LOCATION</th>
              <th>BANK</th>
              <th>DISTRICT</th>
              <th>ACCOUNT</th>
              <th colspan="3">ACTIONS</th>
            </tr>
            </thead>
            <tbody>
            <% @accounts.each do |account| %>
                <tr>
                  <td><%= i %></td>
                  <td><%= account.csp_code.upcase %></td>
                  <td><%= account.name.titleize %></td>
                  <td><%= account.location %></td>
                  <td><%= account.bank_name %></td>
                  <td><%= account.district %></td>
                  <td><%= account.account_number %></td>
                  <td><%= link_to 'View', account, class: 'btn btn-info btn-xs' %> |
                    <%= link_to 'Edit', edit_account_path(account), class: 'btn btn-warning btn-xs' %> |
                    <%= link_to 'Delete ', account, method: :delete, data: {confirm: 'Are you sure to delete the Record?'}, class: 'btn btn-danger btn-xs' %></td>
                </tr>
                <% i = i + 1 %>
            <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
  </div>
</div>

app/views/accounts/new.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      CSP Accounts
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>

      </li>
      <li>
        <i class="fa fa-table"></i>  <%= link_to 'CSP Accounts', accounts_path %>
      </li>

      <li class="active">
        <i class="fa fa-table"></i> Add New CSP Account
      </li>
    </ol>
  </div>
</div>
<!-- Page Heading -->

<div class="panel panel-default">
  <div class="panel-heading">
    Add New Account
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>
<%= link_to accounts_path, class: 'btn btn-success' do %>
    <i class="glyphicon glyphicon-arrow-left"></i> Back to Accounts
<% end %>

app/views/accounts/pdf_export.html.erb
<% i=1 %>
<% total = 0 %>
<p align="center">CSP Accounts Statement </p>
<% if @accounts.blank? %>
    <strong>OPPS!</strong> There are no CSP Accounts in the System.
<% else %>
    <table>
      <thead>
      <tr>
        <th>#</th>
        <th>CSP Code</th>
        <th>Name</th>
        <th>Location</th>
        <th>bank_name</th>
        <th>District</th>
        <th>Account</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @accounts.each do |account| %>
          <tr>
            <td><%= i %></td>
            <td><%= account.csp_code.upcase %></td>
            <td><%= account.name.titleize %></td>
            <td><%= account.location %></td>
            <td><%= account.bank_name %></td>
            <td><%= account.district %></td>
            <td><%= account.account_number %></td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/accounts/show.html.erb
<!-- Page Heading -->
<div class="row">
  <div class="col-lg-12">
    <h2 class="page-header">
      CSP Accounts
    </h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to dashboard_index_path do %>
            <i class="fa fa-home"></i> Home
        <% end %>

      </li>
      <li>
        <i class="fa fa-list"></i>  <%= link_to 'CSP Accounts', accounts_path %>
      </li>

      <li class="active">
        <i class="fa fa-file-o"></i> CSP Account Details
      </li>
    </ol>
  </div>
</div>
<!-- Page Heading -->

<div class="panel panel-default">
  <div class="panel-heading">
    CSP Account Details
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">

      <table class="table table-striped table-bordered">
        <tbody>
        <tr>
          <td data-field="name" data-halign="right" data-align="center">CSP Code</td>
          <td><%= @account.csp_code.upcase %></td>
        </tr>
        <tr>
          <td data-field="stargazers_count" data-halign="center" data-align="left">CSP Name</td>
          <td><%= @account.name.titleize %></td>
        </tr>
        <tr>
          <td data-field="forks_count" data-halign="left" data-align="right">CSP Location</td>
          <td><%= @account.location %></td>
        </tr>
        <tr>
          <td data-field="forks_count" data-halign="left" data-align="right">CSP Mobile</td>
          <td><%= @account.mobile %></td>
        </tr>

        <tr>
          <td data-field="forks_count" data-halign="left" data-align="right">CSP Bank Account</td>
          <td><%= @account.account_number %></td>
        </tr>
        <tr>
          <td data-field="forks_count" data-halign="left" data-align="right">CSP Bank Name</td>
          <td><%= @account.bank_name %></td>
        </tr>
        <tr>
          <td data-field="forks_count" data-halign="left" data-align="right">CSP Branch Name</td>
          <td><%= @account.branch_name %></td>
        </tr>
        <tr>
          <td data-field="forks_count" data-halign="left" data-align="right">CSP Branch Code</td>
          <td><%= @account.branch_code %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to accounts_path, class: 'btn btn-success' do %>
    <i class='glyphicon glyphicon-arrow-left'></i> Back to CSP Accounts
<% end %>&#09;

<%= link_to edit_account_path(@account), class: 'btn btn-warning' do %>
    <i class='glyphicon glyphicon-edit'></i> Edit CSP Account
<% end %>